version: "3.8"
services:
  db:
    image: "docker.io/library/postgres:alpine3.18"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh"
  keycloak:
    image: "docker.io/jboss/keycloak:16.1.1"
    ports:
      - "8090:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/keycloak-config.json
      - DB_VENDOR=postgres
      - DB_ADDR=db:5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=keycloak
    volumes:
      - "./keycloak-config.json:/keycloak-config.json"
      - "keycloak-data:/opt/keycloak/data/"
    depends_on:
      - db
volumes:
  db-data:
  keycloak-data:
